/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.excel.frames;

import br.com.excel.listener.Listener_Importar_Excel;
import java.util.List;
import java.util.Arrays;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author tiago.teixeira
 */
public class Form_Importar_Excel extends javax.swing.JFrame {

    private static final long serialVersionUID = 1209140346638430133L;
    private final Listener_Importar_Excel listener;

    /**
     * Creates new form Form_Main
     */
    public Form_Importar_Excel() {
        initComponents();
        listener = new Listener_Importar_Excel(this);
        dataTest();
    }

    private void dataTest(){
        txtEnderecoBanco.setText("jdbc:derby://10.10.11.158:1527//home/databases/sres_db");
        txtUsuarioBanco.setText("root");
        txtPasswordBanco.setText("Sermed159#%&");
    }
    
    public List<JComponent> getListaBotoes(){
        return Arrays.asList(btTestarConexao, btAddTabela, btCarregar, btRemover, btAddTodas, btRemoverTodas, btSelecionarArquivo);
    }

    public JTabbedPane getTbbPlans() {
        return tbbPlans;
    }

    public JTable getTbTabelaDestOpcao() {
        return tbTabelaDestOpcao;
    }

    public JTable getTbTabelaDestSelecionada() {
        return tbTabelaDestSelecionada;
    }

    public JLabel getLbRespostaTesteConexao() {
        return lbRespostaTesteConexao;
    }

    public JComboBox<String> getCbDriver() {
        return cbDriver;
    }

    public JTextField getTxtEnderecoBanco() {
        return txtEnderecoBanco;
    }

    public JPasswordField getTxtPasswordBanco() {
        return txtPasswordBanco;
    }

    public JTextField getTxtUsuarioBanco() {
        return txtUsuarioBanco;
    }

    public JTextField getTxtArquivo() {
        return txtArquivo;
    }

    public JPanel getPainelDetalhesExcel() {
        return painelDetalhesExcel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMain = new javax.swing.JPanel();
        painelGuias = new javax.swing.JTabbedPane();
        painelEntradaParametros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbRespostaTesteConexao = new javax.swing.JLabel();
        txtEnderecoBanco = new javax.swing.JTextField();
        txtUsuarioBanco = new javax.swing.JTextField();
        txtPasswordBanco = new javax.swing.JPasswordField();
        btTestarConexao = new javax.swing.JButton();
        cbDriver = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtArquivo = new javax.swing.JTextField();
        btSelecionarArquivo = new javax.swing.JButton();
        painelDetalhesExcel = new javax.swing.JPanel();
        painelTabDestino = new javax.swing.JPanel();
        scTabelaDestOpcao = new javax.swing.JScrollPane();
        tbTabelaDestOpcao = new javax.swing.JTable();
        btCarregar = new javax.swing.JButton();
        btAddTabela = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAddTodas = new javax.swing.JButton();
        btRemoverTodas = new javax.swing.JButton();
        scTabelaDestSelecionada = new javax.swing.JScrollPane();
        tbTabelaDestSelecionada = new javax.swing.JTable();
        painelArquivoExcel = new javax.swing.JPanel();
        scPlans = new javax.swing.JScrollPane();
        tbbPlans = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Importar Registros do Excel");

        painelMain.setName(""); // NOI18N

        jLabel1.setText("Endereço JDBC do Banco de Dados");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        jLabel4.setText("Driver Client do Banco de Dados");

        btTestarConexao.setText("Testar Conexão");
        btTestarConexao.setActionCommand("testarConexao");

        cbDriver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "org.apache.derby.jdbc.ClientDriver", "com.mysql.jdbc.Driver", "org.postgresql.Driver", "oracle.jdbc.OracleDriver" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Informações necessárias para fazer upload dos registros para o banco de dados. Nenhum dos dados aqui fornecidos serão gravados.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Arquivo de dados do Excel que será utilizado como fonte de registros.");

        jLabel7.setText("Arquivo de Dados");

        txtArquivo.setEditable(false);

        btSelecionarArquivo.setText("Selecionar Arquivo");
        btSelecionarArquivo.setActionCommand("selecionarArquivo");

        painelDetalhesExcel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout painelEntradaParametrosLayout = new javax.swing.GroupLayout(painelEntradaParametros);
        painelEntradaParametros.setLayout(painelEntradaParametrosLayout);
        painelEntradaParametrosLayout.setHorizontalGroup(
            painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEntradaParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelDetalhesExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelEntradaParametrosLayout.createSequentialGroup()
                        .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecoBanco)
                            .addGroup(painelEntradaParametrosLayout.createSequentialGroup()
                                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuarioBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPasswordBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(painelEntradaParametrosLayout.createSequentialGroup()
                                .addComponent(btTestarConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbRespostaTesteConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbDriver, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelEntradaParametrosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEntradaParametrosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btSelecionarArquivo))
                            .addComponent(txtArquivo))))
                .addContainerGap())
        );
        painelEntradaParametrosLayout.setVerticalGroup(
            painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEntradaParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEnderecoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuarioBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswordBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTestarConexao)
                    .addComponent(lbRespostaTesteConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEntradaParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSelecionarArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDetalhesExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelGuias.addTab("Banco de Dados", painelEntradaParametros);

        tbTabelaDestOpcao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scTabelaDestOpcao.setViewportView(tbTabelaDestOpcao);

        btCarregar.setText("Carregar");
        btCarregar.setActionCommand("carregarTabelas");

        btAddTabela.setText("Adicionar");
        btAddTabela.setActionCommand("addTabelaDestino");

        btRemover.setText("Remover");
        btRemover.setActionCommand("removeTabelaDestino");

        btAddTodas.setText("Add Todas");
        btAddTodas.setActionCommand("addTodas");

        btRemoverTodas.setText("Remover Todas");
        btRemoverTodas.setActionCommand("removerTodas");

        tbTabelaDestSelecionada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scTabelaDestSelecionada.setViewportView(tbTabelaDestSelecionada);

        javax.swing.GroupLayout painelTabDestinoLayout = new javax.swing.GroupLayout(painelTabDestino);
        painelTabDestino.setLayout(painelTabDestinoLayout);
        painelTabDestinoLayout.setHorizontalGroup(
            painelTabDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scTabelaDestOpcao, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTabDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAddTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAddTodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemoverTodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scTabelaDestSelecionada, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelTabDestinoLayout.setVerticalGroup(
            painelTabDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTabDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTabDestinoLayout.createSequentialGroup()
                        .addComponent(btCarregar)
                        .addGap(78, 78, 78)
                        .addComponent(btAddTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAddTodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoverTodas)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addComponent(scTabelaDestSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(scTabelaDestOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelGuias.addTab("Tabela de Destino", painelTabDestino);

        scPlans.setBorder(null);

        tbbPlans.setMaximumSize(new java.awt.Dimension(776, 354));
        tbbPlans.setPreferredSize(new java.awt.Dimension(776, 354));
        scPlans.setViewportView(tbbPlans);

        javax.swing.GroupLayout painelArquivoExcelLayout = new javax.swing.GroupLayout(painelArquivoExcel);
        painelArquivoExcel.setLayout(painelArquivoExcelLayout);
        painelArquivoExcelLayout.setHorizontalGroup(
            painelArquivoExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPlans, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        painelArquivoExcelLayout.setVerticalGroup(
            painelArquivoExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPlans, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        painelGuias.addTab("Arquivo Excel", painelArquivoExcel);

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMainLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelGuias))
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGuias, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Importar_Excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Importar_Excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Importar_Excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Importar_Excel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Importar_Excel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddTabela;
    private javax.swing.JButton btAddTodas;
    private javax.swing.JButton btCarregar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btRemoverTodas;
    private javax.swing.JButton btSelecionarArquivo;
    private javax.swing.JButton btTestarConexao;
    private javax.swing.JComboBox<String> cbDriver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbRespostaTesteConexao;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel painelArquivoExcel;
    private javax.swing.JPanel painelDetalhesExcel;
    private javax.swing.JPanel painelEntradaParametros;
    private javax.swing.JTabbedPane painelGuias;
    private javax.swing.JPanel painelMain;
    private javax.swing.JPanel painelTabDestino;
    private javax.swing.JScrollPane scPlans;
    private javax.swing.JScrollPane scTabelaDestOpcao;
    private javax.swing.JScrollPane scTabelaDestSelecionada;
    private javax.swing.JTable tbTabelaDestOpcao;
    private javax.swing.JTable tbTabelaDestSelecionada;
    private javax.swing.JTabbedPane tbbPlans;
    private javax.swing.JTextField txtArquivo;
    private javax.swing.JTextField txtEnderecoBanco;
    private javax.swing.JPasswordField txtPasswordBanco;
    private javax.swing.JTextField txtUsuarioBanco;
    // End of variables declaration//GEN-END:variables
}
